import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin } from 'react-icons/ai';
import { useState } from 'react';
//import design from '../public/code.png';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>FQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb=12 flex justify-between'>
            <h1 className='text-xl font-mono'>Hola</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  href='#'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Fernando Quero</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Full Stack Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl mx-w-xl mx-auto'>Thingssss to say.</p>
          </div>
          <div className='text-5xl flex justify-center gap-6 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              This is the beginnin of my journey as a developer.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              {/* <Image src={#} width={100} height={100} />  */}
              <h3 className='text-lg font-medium pt-8 pb-2'>Coding designs</h3>
              <p className='py-2'>sdfsadfasdf</p>
              <h4 className='py-4 text-teal-600'>sadfasdfsadfsadf</h4>
              <p className='text-gray-800 py-1'>phtoo</p>
              <p className='text-gray-800 py-1'>illura</p>
              <p className='text-gray-800 py-1'>fi</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              {/* <Image src={#} width={100} height={100} /> */}
              <h3 className='text-lg font-medium pt-8 pb-2'>Coding designs</h3>
              <p className='py-2'>sdfsadfasdf</p>
              <h4 className='py-4 text-teal-600'>sadfasdfsadfsadf</h4>
              <p className='text-gray-800 py-1'>phtoo</p>
              <p className='text-gray-800 py-1'>illustra</p>
              <p className='text-gray-800 py-1'>figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
          </div>
        </section>
      </main>
    </div>
  );
}
